imports:
    - { resource: ../../../../src/Machine/Shared/Infrastructure/Symfony/DependencyInjection/machine_services.yaml }
parameters:
  locale: ~
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    VendingMachine\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ 'vendingmachine.domain_event_subscriber' ]
    VendingMachine\Shared\Domain\Bus\Command\CommandHandler:
      tags: [ 'vendingmachine.command_handler' ]
    VendingMachine\Shared\Domain\Bus\Query\QueryHandler:
      tags: [ 'vendingmachine.query_handler' ]

  VendingMachine\Apps\Vending\Backend\Command\:
    resource: '../src/Command'
    tags: [ 'console.command' ]

  VendingMachine\Shared\:
    resource: '../../../../src/Shared/*'

  VendingMachine\Machine\:
    resource: '../../../../src/Machine/*'

  VendingMachine\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged vendingmachine.domain_event_subscriber ]
    lazy: true

  VendingMachine\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [ !tagged vendingmachine.database_connection ]

  VendingMachine\Shared\Infrastructure\Bus\Command\InMemory\InMemorySymfonyCommandBus:
    arguments: [ !tagged vendingmachine.command_handler ]

  VendingMachine\Shared\Infrastructure\Bus\Query\InMemory\InMemorySymfonyQueryBus:
    arguments: [ !tagged vendingmachine.query_handler ]
